name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Instalar dependências
        run: composer install --no-dev --optimize-autoloader

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
